name: msc-proyecto
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - lightfm
  - scikit-surprise
  - pytorch~=1.9.0
  - jupyter
#  - torchvision
#  - torchaudio
  - pytorch-cuda=11.7
  - pip
  - pip:
    - recommenders